spring:
  application:
    name: notification-service
  profiles:
    active: dev #${env}

#admin client config
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"